### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=a1s5mu&redirect_uri=http://www.51xuecheng.cn

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123

### 校验jwt
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MDkyOTI3OTUsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImJiNmFhNjZiLTBiNTQtNDU2OC05YmEyLTZlNTE5ODZiNDc2YyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.4dNOyrnGU7d-La16fB_Urmt6-hr13NYAWt_oc08Zn0s
